[general]
live_config_reload = false

[scrolling]
history     = 100000
multiplier  = 3



[font]
size = 10.0 

[font.normal]
family = "JetBrains Mono"
style = "Bold"

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"



[cursor]
style  = { shape = "Underline", blinking = "On" }
unfocused_hollow = false



[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background     = "#2a2a2a"
foreground     = "#d8dee9"
dim_foreground = "#a5abb6"


[colors.cursor]
text   = "#2e3440"
cursor = "#d8dee9"


[colors.vi_mode_cursor]
text   = "#2e3440"
cursor = "#d8dee9"


[colors.selection]
background = "#4c566a"
text       = "#d8dee9"


[colors.search]
[colors.search.matches]
foreground = "#2e3440"
background = "#88c0d0"


[colors.footer_bar]
background = "#434c5e"
foreground = "#d8dee9"


[colors.bright]
black   = "#4c566a"
red     = "#bf616a"
green   = "#a3be8c"
yellow  = "#ebcb8b"
blue    = "#81a1c1"
magenta = "#b48ead"
cyan    = "#8fbcbb"
white   = "#eceff4"

[colors.normal]
black   = "#3b4252"
red     = "#bf616a"
green   = "#a3be8c"
yellow  = "#ebcb8b"
blue    = "#81a1c1"
magenta = "#b48ead"
cyan    = "#88c0d0"
white   = "#e5e9f0"

[colors.dim]
black   = "#373e4d"
red     = "#94545d"
green   = "#809575"
yellow  = "#b29e75"
blue    = "#68809a"
magenta = "#8c738c"
cyan    = "#6d96a5"
white   = "#aeb3bb"



[keyboard]
bindings = [
{ key = "+", mods = "Control|Shift", action = "IncreaseFontSize" },
{ key = "Backspace", mods = "Control", chars =  "\u0017"},
]
